// web/src/App.tsx
import { useState } from 'react'
import { Button, Flex } from 'antd'
import FileTable from './components/FileTable'
import UploadModal from './components/UploadModal'
import './App.css'

function App() {
  const [open, setOpen] = useState(false)

  return (
    <>
      <Flex style={{ marginBottom: 20 }}>
        <Button type="primary" onClick={() => setOpen(true)}>
          上传文件
        </Button>
      </Flex>

      <FileTable />

      <UploadModal open={open} onCancel={() => setOpen(false)} />
    </>
  )
}

export default App

// web-vue/src/App.vue
<script setup lang="ts">
import {ref} from 'vue'
import FileTable from './components/FileTable.vue'
import UploadModal from './components/UploadModal.vue'

import MyFileTable from './components/MyFileTable.vue'

const visible = ref(false)
</script>

<template>
  <div style="margin-bottom: 20px; text-align: left">
    <a-button type="primary" @click="visible = true">上传文件</a-button>
  </div>

  <FileTable/>
  <UploadModal v-model:visible="visible"/>


  <div style="margin-bottom: 20px; text-align: left">
    <a-button type="primary" @click="visible = true">我的上传文件</a-button>
  </div>
  <MyFileTable/>
  <UploadModal v-model:visible="visible"/>
</template>

<style>
#app {
  margin: 0 auto;
  padding: 2rem;
  text-align: center;
}
</style>
